### ISSUE TITLE
Feature do not display it  "Vigilance verte" 

### ISSUE THREAD

**Issue by FazCodeFR** [grenagit/MMM-VigilanceMeteoFrance#10]
fr: 
Bonjour, ça serais bien de pouvoir mettre une option qui permet de ne rien afficher si c'est en vigilance verte, j'ai essayer de le faire mais je n'ai pas réussi, merci beaucoup, super module !  

en: 
Hello, it would be nice to be able to put an option to display nothing if it's on green alert, I tried to do it but I couldn't do it, thank you very much, great module!

**Comment by grenagit** [comment]
Duplicate #7

**Comment by grenagit** [comment]
@ABOATDev & @Sidd-9 : Following your requests, the functionality has been added in the [testing branch](https://github.com/grenagit/MMM-VigilanceMeteoFrance/tree/testing).

To **hide module** when the **vigilance level** is **green**, just add `hideGreenLevel: true,` in your **configuration**.

*You are ready to test this on your MagicMirror before publishing the new version in the master branch?*
```sh
cd ~/MagicMirror/modules/MMM-VigilanceMeteoFrance
git checkout testing
git pull
```

Thanks :wink:

**Comment by FazCodeFR** [comment]
Bonjour j'ai testé, le Vigilance verte n'apparait pas, c'est très bien 
Merci beaucoup pour le travail ! 

Hello, I tested, the green Vigilance does not appear, it's very good. 
Thank you very much for the work!

**Comment by grenagit** [comment]
Close by  #12
