### ISSUE TITLE
Pollen

### ISSUE THREAD

**Issue by ricotte38** [grenagit/MMM-VigilanceMeteoFrance#11]
Bonjour,

est il possible d'ajouter l'etat du pollen das le modules ?

Merci par avance

Rico

**Comment by grenagit** [comment]
@ricotte38 : Tu devrais trouver ton bonheur avec ce tout nouveau module : [MMM-VigilancePollensFrance](https://github.com/grenagit/MMM-VigilancePollensFrance) !

![MMM-VigilancePollensFrance Screenshots](https://github.com/grenagit/MMM-VigilancePollensFrance/raw/master/MMM-VigilancePollensFrance_screenshots.png)

**Comment by ricotte38** [comment]
Top 
Merci Beaucoup!
