### ISSUE TITLE
Please set the correct apiConsumerKey and apiConsumerSecret in the config for module: MMM-VigilanceMeteoFrance

### ISSUE THREAD

**Issue by Selyjohns** [grenagit/MMM-VigilanceMeteoFrance#14]
Bonjour,

J'ai mis à jour le module dans sa dernière version.
Depuis, il ne fonctionne plus et affiche l'erreur suivante :

`Please set the correct apiConsumerKey and apiConsumerSecret in the config for module: MMM-VigilanceMeteoFrance`

La documentation ne semble rien indiquer à ce sujet.
Est-ce que j'ai raté quelque chose ?

(le retour sur l'ancienne version ne pose pas de problème)

**Comment by grenagit** [comment]
Bonjour @josselynL,

La mise à jour de la dernière version n'a été poussée, pour l'instant, que sur la **branche " testing "**, il faut dont [regarder ici](https://github.com/grenagit/MMM-VigilanceMeteoFrance/tree/testing) pour la documentation à jour !

Pour confirmer que tu es bien sur la **branche " testing "** :
```
cd ~/MagicMirror/modules/MMM-VigilanceMeteoFrance
git branch -v
```

Pour retourner sur la **branche principale " master "** :
```
cd ~/MagicMirror/modules/MMM-VigilanceMeteoFrance
git checkout master
```

_Après, je suis aussi preneur de ton retour sur la nouvelle version du module utilisant l'API de MétéoFrance 😁_

**Comment by Selyjohns** [comment]
> Bonjour @josselynL,
> 
> La mise à jour de la dernière version n'a été poussée, pour l'instant, que sur la **branche " testing "**, il faut dont [regarder ici](https://github.com/grenagit/MMM-VigilanceMeteoFrance/tree/testing) pour la documentation à jour !
> 
> Pour confirmer que tu es bien sur la **branche " testing "** :
> 
> ```
> cd ~/MagicMirror/modules/MMM-VigilanceMeteoFrance
> git branch -v
> ```
> 
> Pour retourner sur la **branche principale " master "** :
> 
> ```
> cd ~/MagicMirror/modules/MMM-VigilanceMeteoFrance
> git checkout master
> ```
> 
> _Après, je suis aussi preneur de ton retour sur la nouvelle version du module utilisant l'API de MétéoFrance 😁_

Merci de ton retour rapide !
Surement en effet ! J'ai généré mes identifiants d'accés à l'API, je test ça des que possible et je te fais un retour ! 😊

il va falloir que le module meteo nativement inclus intègre l'API de meteofrance parce que desfois c'est pas ça 😅 !

**Comment by Selyjohns** [comment]
Hello,
En effet je suis sur la testing :)
Tout semble OK après ajout des infos dans le config.js, belle évolution.

Je te tiens informé si je rencontre un problème.
Belle journée.
