### ISSUE TITLE
Transposition dans Home Assistant

### ISSUE THREAD

**Issue by Userfreedu42** [grenagit/MMM-VigilanceMeteoFrance#15]
Bonjour et merci pour tes développements,
J'ai un compte sur le portail des api de MétéoFrance et on peut exécuter des scripts sous Home assistant
Penses tu que les tiens seraient transposables ?

**Comment by grenagit** [comment]
> Bonjour et merci pour tes développements

Bonjour et merci :smile: 

> J'ai un compte sur le portail des api de MétéoFrance et on peut exécuter des scripts sous Home assistant Penses tu que les tiens seraient transposables ?

Oui l'accès aux [API Météo France](https://portail-api.meteofrance.fr/devportal/) se fera de manière similaire (le but d'une API étant que les données puissent être consommées indépendamment du language de programmation).

_HomeAssistant_, je connais juste de nom mais il semble qu'un [module MétéoFrance](https://www.home-assistant.io/integrations/meteo_france/) existe et qu'il est codé en **Python** (contrairement à _MagicMirror_ qui est en **JS** / **NodeJs**)...

**Comment by Userfreedu42** [comment]
Effectivement mais elle ne fonctionne plus pour la vigilance météo
