### ISSUE TITLE
Chargement du module 15 jours

### ISSUE THREAD

**Issue by ricotte38** [grenagit/MMM-VigilanceMeteoFrance#16]
Bonjour,

Utilisateur de ce module depuis plusieurs années, celui ci reste en chargement depuis une quinzaine de jours.
Sauriez vous pourquoi? est ce dû à l’évolution de l'api météo vigilance qui intègre les crus?

Si vous avez une solution?

Merci d'avance

**Comment by ricotte38** [comment]
Par ailleurs plusieurs liens sur la page du module ne retrouve pas leur chemin;)
Merci

**Comment by grenagit** [comment]
Bonjour @ricotte38 

> Utilisateur de ce module depuis plusieurs années, celui ci reste en chargement depuis une quinzaine de jours. Sauriez vous pourquoi? est ce dû à l’évolution de l'api météo vigilance qui intègre les crus?

Avez-vous vérifier que votre API Consumer Key et votre API Consumer Secret correspondaient bien avec celles du [portail API](https://portail-api.meteofrance.fr/devportal/applications/) ? J'arrive à la conclusion que les miennes ont changées...

> Par ailleurs plusieurs liens sur la page du module ne retrouve pas leur chemin;)

C'est corrigé !

**Comment by ricotte38** [comment]
Hello,

Merci beaucoup, en effet mes api n’étaient sans doute plus à jour...

Au top, merci encore
