### ISSUE TITLE
Probleme de Lien

### ISSUE THREAD

**Issue by ricotte38** [grenagit/MMM-VigilanceMeteoFrance#18]
Bonjour, 

Merci pour ce module que j'utilise depuis très longtemps.
Je viens de faire la mise à jour et je constate que vos liens ne se redirige pas pour obtenir l'appid .

Et comme je ne peux plus utiliser les anciens j'ai dû mettre celui que vous proposez.

J'aurai bien voulu avoir mon propre appid, pouvez vous actualiser les liens?

Merci d'avance

**Comment by Fabaude** [comment]
Bonjour,
exactement le même problème de mon côté !

En tout cas, module bien pratique .

Merci

**Comment by grenagit** [comment]
Bonjour,

Les liens sont bons, il s'agit d'un problème d'indisponibilité du portail API de MétéoFrance !
Merci de ré-essayer plus tard.

**Comment by ricotte38** [comment]
https://portail-api.meteofrance.fr/web/fr/
