### ISSUE TITLE
Ecran noir

### ISSUE THREAD

**Issue by Kadezaid** [grenagit/MMM-VigilanceMeteoFrance#19]
Bonjour et merci beaucoup pour ce module que j'utilise depuis des années !

Je viens de faire la MàJ avec cette config très simple ;
```
		{
			module: "MMM-VigilanceMeteoFrance",
			position: "top_left",
			config: {
				appid: "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX",
				department: 35,
			}
		},
```
Lors de redémarrage de MM, mon écran devient noir et plus aucuns modules ne s'affiche...

Le seul moyen est de commenté ces lignes puis faire un reboot de MM.
Il se relance normalement sans afficher VigilanceMeteoFrance.

Avez-vous une idée ?

**Comment by grenagit** [comment]
> Je viens de faire la MàJ

MàJ du module ? De MagicMirror ? De Raspberry Pi OS ?

> Lors de redémarrage de MM, mon écran devient noir et plus aucuns modules ne s'affiche...

Je n'ai pas réussi à reproduire ce bug avec la config suivante  ! Quelque chose dans la console ou les journaux de MagicMirror ?
```
		{
			module: "MMM-VigilanceMeteoFrance",
			position: "top_left",
			header: "Vigilance Météo France",
			//disabled: true, // MODULE DESACTIVE
			config: {
			        appid: "WkU5X0NvWDRKODJ2THE0OUw1b2FyVEN0OFdZYTpla3hQb1ZqMmRQaXJ3c0pYcnNzRUFZM1kxUnNh",
				department: 35,
			}
		},
```

> Le seul moyen est de commenté ces lignes puis faire un reboot de MM.
> Il se relance normalement sans afficher VigilanceMeteoFrance.

Cela laisse en effet penser que le problème vient de MMM-VigilanceMeteoFrance :confused:

**Comment by Kadezaid** [comment]
Pardon, oui MàJ du module, pour MM je suis en 2.14.0 (Je viens d'essayer de faire une MàJ de MM, mais là aussi écran noir... Je suis donc repartie sur 2.14.0).

J'ai essayé avec ta config, cela ne marche pas non plus...

Comment accèdent on au journaux de MM ? J'y mettrais le rapport.

Merci pour ta réponse tres rapide!

**Comment by grenagit** [comment]
> oui MàJ du module,

As-tu bien suivi la procédure ?
```
cd ~/MagicMirror/modules/MMM-VigilanceMeteoFrance
git pull
npm install
```

As-tu eu quelque chose de particulier lors de ces opérations ?
Si non, tu peux tenter une réinstallation complète du module :
```
rm -r ~/MagicMirror/modules/MMM-VigilanceMeteoFrance
cd ~/MagicMirror/modules
git clone https://github.com/grenagit/MMM-VigilanceMeteoFrance
cd ~/MagicMirror/modules/MMM-VigilanceMeteoFrance
npm install
```

> pour MM je suis en 2.14.0

Une version qui date de plus de 3 ans ! Moi, je commencerai déjà par faire la mise à jour [2.14.0](https://github.com/MagicMirrorOrg/MagicMirror/releases/tag/v2.14.0) > [2.27.0](https://github.com/MagicMirrorOrg/MagicMirror/releases/tag/v2.27.0) avec NodeJS et le système si besoin...

> Comment accèdent on au journaux de MM ? J'y mettrais le rapport.

Il lancer MM en mode dev et utiliser la console intégrée aux outils de développement. Tu peux filtrer les informations avec `MMM-VigilanceMeteoFrance`.

```
cd ~/MagicMirror/
npm run start:dev
```

Tu devrais avoir quelque chose comme ça (exemple avec un autre module) :

![](https://github.com/grenagit/MMM-PIR-Sensor-Lite/raw/master/MMM-PIR-Sensor-Lite_console-log.png)

**Comment by Kadezaid** [comment]
Bonjour,

j'ai du refaire une install complet de MM, impossible de faire une mise a jour...

Et tout fonctionne a présent !

Les Modules que j'avais mis me suffisait depuis 3/4 ans et ils étaient stables, donc j'ai jamais eu le besoin de faire de mise à jour.
Je l'avais quand même fait une fois et tout avait planté, donc je n'avait jamais vraiment voulu réessayé.

Erreur bête et classique...

Merci pour quand même beaucoup.
