### ISSUE TITLE
load...

### ISSUE THREAD

**Issue by chassain** [grenagit/MMM-VigilanceMeteoFrance#4]
hello,

a problem today with this beautiful module..display load only after a restart mm..no change during the day..

Have a good day

**Comment by grenagit** [comment]
@chassain Thank you for reporting the problem quickly!

Météo France has updated its [vigilance service](https://vigilance.meteofrance.fr) with some small changes in the URL...

After a little update of the module, it should be in order ;-)
```shell
cd ~/MagicMirror/modules/MMM-VigilanceMeteoFrance
git pull
```

**Comment by chassain** [comment]
work fine...MERCIIIIIIIII
