### ISSUE TITLE
removing the top bar notification

### ISSUE THREAD

**Issue by alexhoud** [grenagit/MMM-VigilanceMeteoFrance#9]
Hi, 

Thanks for your nice Module :) Very useful now in France!
But please I would like to remove the top bar notification saying : "Vigilance Météo France / Attention, votre département est placé en vigilance jaune!" and only keep the coloroured notif (the one I can choose the place)
Actually this notif bar is at the clock place for me..

Is it possible ?
Merci ;)

**Comment by alexhoud** [comment]
Ok I just modified the time of notificationDuration and decrease it;)
Now it deassapear faster and I can see my clock ;)

Encore merci!

**Comment by grenagit** [comment]
> Thanks for your nice Module :) Very useful now in France!

Thanks :+1: 

> But please I would like to remove the top bar notification saying : "Vigilance Météo France / Attention, votre département est placé en vigilance jaune!" and only keep the coloroured notif (the one I can choose the place)
> Is it possible ?

Yes of course, it is possible to disable notifications (level of vigilance change or new risks) with `showNotification: false,` in your configuration file !
